name: 'GitHub Action Atmos Component Updater'
description: 'GitHub Action Atmos Component Updater'
author: hello@cloudposse.com
branding:
  icon: 'server'
  color: 'white'
inputs:
  param1:
    required: true
    description: "Input parameter placeholder"
    default: "true"
outputs:
  result1:
    description: "Output result placeholder"
    value: "${{ steps.context.outputs.action-result }}"
runs:
  using: "composite"
  steps:
    - id: context
      shell: bash
      run: |
          echo "::set-output name=action-result::${{ inputs.param1 }}"

