name: 'GitHub Action Atmos Component Updater'
description: 'GitHub Action Atmos Component Updater'
author: hello@cloudposse.com
branding:
  icon: 'server'
  color: 'white'
inputs:
  token:
    required: true
    description: "Private Access Token"
runs:
  using: "composite"
  steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v3

    - name: "Setup Python"
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: "Install Python Dependencies"
      run: |
        pip install -r src/requirements.txt

    - name: "Test"
      run: |
        echo "test"
