name: 'GitHub Action Atmos Component Updater'
description: 'GitHub Action Atmos Component Updater'
author: hello@cloudposse.com
branding:
  icon: 'server'
  color: 'white'
inputs:
  github-access-token:
    description: "GitHub Token used to perform git and GitHub operations"
    required: false
    default: ${{ github.token }}
  infra-terraform-dirs:
    description: "Comma or new line separated list of terraform directories in infra repo. For example 'components/terraform,components/terraform-old. Default 'components/terraform'"
    required: false
    default: 'components/terraform'
  vendoring-enabled:
    description: "Do not perform 'atmos vendor component-name' on components that wasn't vendored"
    required: false
    default: 'true'
  max-number-of-prs:
    description: "Number of PRs to create. Maximum is 10."
    required: false
    default: '10'
  include:
    description: "Comma or new line separated list of component names to include. For example: 'vpc,eks/*,rds'. By default all components are included. Default '*'"
    required: false
    default: '*'
  exclude:
    description: "Comma or new line separated list of component names to exclude. For example: 'vpc,eks/*,rds'. By default no components are excluded. Default ''"
    required: false
    default: ''
  atmos-version:
    description: "Atmos version to use for vendoring. Default 'latest'"
    required: false
    default: 'latest'
  log-level:
    description: "Log level for this action. Default 'INFO'"
    required: false
    default: 'INFO'
  dry-run:
    description: "Skip creation of remote branches and pull requests. Only print list of affected componented into file that is defined in 'outputs.affected-components-file'"
    required: false
    default: 'false'
  pr-labels:
    description: "Comma or new line separated list of labels that will added on PR creation. Default: `component-update`"
    required: false
    default: 'component-update'
  pr-title-template:
    description: "A string representing a Jinja2 formatted template to be used as the content of a Pull Request (PR) title. If not, set template from `src/templates/pr_title.j2.md` will be used"
    required: false
    default: ''
  pr-body-template:
    description: "A string representing a Jinja2 formatted template to be used as the content of a Pull Request (PR) body. If not set template from `src/templates/pr_body.j2.md` will be used"
    required: false
    default: ''
outputs:
  affected:
    description: The affected components
  has-affected-stacks:
    description: Whether there are affected components
runs:
  using: "docker"
  image: 'Dockerfile'
  env:
    GITHUB_ACCESS_TOKEN: ${{ inputs.github-access-token }}
    INFRA_TERRAFORM_DIRS: ${{ inputs.infra-terraform-dirs }}
    VENDORING_ENABLED: ${{ inputs.vendoring-enabled }}
    MAX_NUMBER_OF_PRS: ${{ inputs.max-number-of-prs }}
    INCLUDE: ${{ inputs.include }}
    EXCLUDE: ${{ inputs.exclude }}
    LOG_LEVEL: ${{ inputs.log-level }}
    DRY_RUN: ${{ inputs.dry-run }}
    PR_LABELS: ${{ inputs.pr-labels }}
    PR_TITLE_TEMPLATE: ${{ inputs.pr-title-template }}
    PR_BODY_TEMPLATE: ${{ inputs.pr-body-template }}
